### PR TITLE
Support of neos 3.x

### PR DESCRIPTION
**Pull request by volkc**
Hey guys,

i've just modified your code that it works with the recent neos release (3.0). Maybe you wan't to merge that stuff into your base branch. 

Kind regards,
Chris

### CODE REVIEW

**Comment by dlubitz** [comment]
Hi @dfeyer, are there any plans to merge the PR of @volkc in next time?

**Comment by kdambekalns** [comment]
Hi, @dfeyer - this would really be a useful merge & release together with `ttree/script` after https://github.com/ttreeagency/Script/pull/1 …

**Comment by kdambekalns** [comment]
I took that PR and amended it with some more changes in https://github.com/kdambekalns/Map/tree/neos-3-compatibility.

@volkc I created a PR against your fork (https://github.com/volkc/Map/pull/1) - but of course if @dfeyer likes, he can just create PR directly from my fork as well.

Thanks!

**Comment by dlubitz** [comment]
thanks @dfeyer

**Pull request merged**
